import Head from "next/head";
import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import { RingLoader, CircleLoader, HashLoader } from "react-spinners";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ value }) {
  // console.log("Index", typeof Home);
  return (
    <div>
      <Head>
        <title>Wangsap Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          display: "flex",
          // justifyContent: "space-evenly",
          width: "85%",
          margin: "auto",
          alignItems: "center",
          marginTop: "2vh",
        }}
      >
        <Sidebar />
        <div style={{ marginLeft: "15%" }}>
          <div style={{ display: "flex", justifyContent: "space-around" }}>
            <RingLoader color="#36d7b7" />
            <HashLoader color="#36d7b7" />
            <CircleLoader color="#36d7b7" />
          </div>
          <marquee style={{ color: "#36d7b7", marginTop: "2vh" }}>
            Start a Chat or Chat Developer for Collaboration: jonajr05@gmail.com
          </marquee>
        </div>
      </div>
    </div>
  );
}
